### ISSUE TITLE
Trying to use on Magnifier

### ISSUE THREAD

**Issue by xSeekTruthx** [benbuck/rbtray#15]
Thank you for making this!

Only want to use for Magnifier App. Windows 10 forces Magnifier window to take up space on the task bar when minimized. I'm trying to make windows 10 zooming function as close to compiz native zooming (ubuntu) as possible.

Right-Clicking its minimize button - no result
Shift-Right-Clicking on its title bar - no result
Using the Windows-Alt-Down hotkey - Windows attempted to do it, the window minimized, stayed in taskbar, an icon appeared in systray, and disappeared when hovering over it in systray.

Any assistance would be appreciated.

**Comment by benbuck** [comment]
Hi @xSeekTruthx,

I've verified that I see the same thing as you, but so far I haven't had time to dig deeper. It may be a limitation of how the Magnifier app is implemented, but I'll keep this open until I can investigate.

Benbuck

**Comment by benbuck** [comment]
Hi @xSeekTruthx,

I'm not 100% sure how Magnifier is implemented, but I'm guessing it's overlaying a full screen image on top of the entire screen, so when you think you're interacting with windows, you're really interacting with that image, and your actions are being mapped to the real windows. With that assumption, I'm going to mark this as Won't Fix, because I don't think there's anything I can do about it unfortunately. Please let me know if you think I'm missing something.

Thanks,
Benbuck
