### ISSUE TITLE
Is it possible to select the left mouse button as Minimize?

### ISSUE THREAD

**Issue by pro100Hub** [benbuck/rbtray#19]
Hello.
Tell please, can you add this feature? For example, I want Mozilla Firefox to be minimized to tray not by the right mouse button but by the left mouse button. Reassigning the mouse button to the left in some applications.

Regards.

**Comment by benbuck** [comment]
Hi @pro100Hub,

It sounds like you are asking for a normal minimize operation (left-clicking on the minimize button) to minimize to the tray instead of the task bar? Is that right? If so, how would you do a normal minimize to the task bar?

-Benbuck

**Comment by pro100Hub** [comment]
Maybe swap them? The left mouse button minimizes the browser to tray, and the right button to the taskbar.
Is it possible?

**Comment by benbuck** [comment]
Hi @pro100Hub.

Since RBTray is Right Button Tray, it sounds like you want LBTray. 😄 

Could you help me understand this a little better, is there a reason the three existing methods for minimizing to the tray don't work for your needs? Is it that just you always want the default behavior to be to minimize to tray, not to task bar? Or is it something like you use the buttons swapped? Or something else?

In general I can say that I want to avoid adding configuration options to RBTray to keep it as simple as possible, and since all the current users want the right button to minimize to tray instead of left, I'm not sure how this would fit in with your request.

Thanks,
Benbuck

**Comment by pro100Hub** [comment]
@benbuck 
> Could you help me understand this a little better, is there a reason the three existing methods for minimizing to the tray don't work for your needs?

I’m used to the [MinimizeToTray](https://addons.thunderbird.net/ru/thunderbird/addon/minimizetotray-revived/) extension that was available for Firefox 56 and below. The left button to minimize to tray is familiar to me in Firefox browser.
If this is possible, you can optionally add an option that will swap the minimize to the taskbar and tray as I suggested earlier. I doubt that the additional option will greatly increase the size of RBTray. There will be practically no changes, but the new feature will certainly be useful and necessary.

Regards.

**Comment by benbuck** [comment]
Hi @pro100Hub,

Ah, I think I used to use the MinimizeToTray extension for Thunderbird long ago also, sorry to hear that doesn't work any more. Even with this, I still don't understand your request fully, if RBTray somehow could minimize to tray by left-clicking on the minimize button, then *all* normal windows would behave like this, not just Firefox. Is that really what you are requesting?

If so, it sounds like it would be better to implement that as a completely separate utility, I really don't want to add that option to RBTray.

Benbuck

**Comment by benbuck** [comment]
Hi @pro100Hub,

I'm going to close this as wontfix, please let me know if you'd like to follow up further.

Thanks,
Benbuck
