### ISSUE TITLE
New Alexa App Partially Minimizes to Tray

### ISSUE THREAD

**Issue by drmoisan** [benbuck/rbtray#51]
The app works perfectly except for the new Alexa PC App. It partially minimizes to the tray but leaves the icon on the taskbar. When I click on the icon on the taskbar, it will not maximize. Meanwhile, there is a generic application card that appears in the system tray. It has the tag Alexa when I hover, but no Alexa icon. When I click on it, it operates successfully. 
![AlexaPartiallyMinimized](https://user-images.githubusercontent.com/54180981/99832442-87193c00-2b2e-11eb-9bd5-733f2524438e.png)

**Comment by platima** [comment]
Hey this appears to be something to do with UWP or Store apps. I installed the Your Phone app, and it does exactly the same thing. I note that it also persists as a window with black contents in the app switcher (alt tab).

Others I quickly tested that fail; Messenger, iTunes, Wacom Inkspace, Whiteboard... I thought all Windows Store apps for a moment, but Debian and Windows Terminal work fine. Possibly because they are built around the conhost framework or something

W10 2004. RBTray 4.1.1

**Comment by benbuck** [comment]
Hi @drmoisan and @platima,

This has been reported before, but I thought it was fixed with the latest Windows releases. Could you please look at issue #22 and add any new information that might help identify this problem into that issue?

Thanks,
Benbuck

**Comment by platima** [comment]
Ah my bad. Did not see that one as it's marked CLOSED.

Will add comments there. Good if you could open it?
